version: '3.7'

services:

  web:
    container_name: lms_frontend
    build: .
    volumes:
      - './:/opt/lms_frontend'
      - '/lms_frontend/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm start